package nl.viasalix.horarium.zermelo.model

data class User(
    var code: String = "",
    var totpSecret: String = "",
    var totpInterval: Int = -1,
    var totpAlgorithm: String = "",
    var totpEnabled: Boolean = false,
    var tfaMandatory: Boolean = false,
    var roles: List<Any> = emptyList(),
    var ldap: Boolean = false,
    var username: String = "",
    var userPrincipalName: String = "",
    var someUUID: String = "",
    var magisterUUID: String = "",
    var isStudent: Boolean = false,
    var isEmployee: Boolean = false,
    var isFamilyMember: Boolean = false,
    var firstName: String = "",
    var prefix: String = "",
    var lastName: String = "",
    var gender: String = "",
    var email: String = "",
    var emailVerified: String = "",
    var street: String = "",
    var city: String = "",
    var dateOfBirth: String = "",
    var schoolInSchoolYears: List<Int> = emptyList(),
    var archived: Boolean = false,
    var hasPassword: Boolean = false,
    var houseNumber: String = "",
    var postalCode: String = "",
    var isApplicationManager: Boolean = false,
    var isSchoolScheduler: Boolean = false,
    var isSchoolLeader: Boolean = false,
    var isStudentAdministrator: Boolean = false,
    var isTeamLeader: Boolean = false,
    var isSectionLeader: Boolean = false,
    var isMentor: Boolean = false,
    var isParentTeacherNightScheduler: Boolean = false,
    var isDean: Boolean = false,
    var displayName: String = ""
)